compile main file without symbol missing error
    $ javac -sourcepath src -cp src:lib/* src/net/coprg/coprg/CoProgramming.java 
    src/net/coprg/coprg/GDrive.java:17: error: cannot find symbol
    import net.coprg.coprg.ProcessStreamHandler;
                          ^
      symbol:   class ProcessStreamHandler
      location: package net.coprg.coprg
    src/net/coprg/coprg/GDrive.java:303: error: cannot find symbol
            ProcessStreamHandler psh = null;
            ^
      symbol:   class ProcessStreamHandler
      location: class GDrive
    src/net/coprg/coprg/GDrive.java:308: error: cannot find symbol
                psh = new ProcessStreamHandler(process.getErrorStream());
                          ^
      symbol:   class ProcessStreamHandler
      location: class GDrive
    3 errors